### ISSUE TITLE
dataProvider.updateLayersData is not a function

### ISSUE THREAD

**Issue by vrman** [visgl/flowmap.gl#27]
i got this error message when , deckgl 8.9.8 , flowmap 8.0.0-alpha.25 .
`` deck: initialization of CompositeLayer({id: 'my-flowmap-layer'}): dataProvider.updateLayersData is not a function ``

is there any solution to fix this?

**Comment by ilyabo** [comment]
Make sure you have the same versions of both libraries installed:


    "@flowmap.gl/data": "^8.0.0-alpha.25",
    "@flowmap.gl/layers": "^8.0.0-alpha.25",

**Comment by vrman** [comment]
they both are same in my project , is my data correct for flowmap ? here is my object :
both is same , my data is : 
```
const data = {
  locations: [
    { id: 1, name: 'New York', lat: 40.713543, lon: -74.011219 },
    { id: 2, name: 'London', lat: 51.507425, lon: -0.127738 },
    { id: 3, name: 'Rio de Janeiro', lat: -22.906241, lon: -43.180244 },
  ],
  flows: [
    { origin: 1, dest: 2, count: 42 },
    { origin: 2, dest: 1, count: 51 },
    { origin: 3, dest: 1, count: 50 },
    { origin: 2, dest: 3, count: 40 },
    { origin: 1, dest: 3, count: 22 },
    { origin: 3, dest: 2, count: 42 },
  ],
}
```

**Comment by ilyabo** [comment]
The data looks good. Could you share your app e.g. on codesandbox?

**Comment by vrman** [comment]
by remove npm cached files and install again , it fixed,
thanks
