### ISSUE TITLE
@flowmap.gl/data latest vertion not match

### ISSUE THREAD

**Issue by lalagis** [visgl/flowmap.gl#37]
Since I run `pnpm upgrade` to the latest @flowmap 8.0.0-alpha27, the error comes:
```
deck: initialization of CompositeLayer({id: 'flowmap-layer'}): dataProvider.updateLayersData is not a function TypeError: dataProvider.updateLayersData is not a function
```
basemap render sucessfully, but the flows hidden.
So I check the lock file, I found that @flowmap.gl/layers version is up to 27, but the @flowmap.gl/data version is `8.0.0-y.14`. Downgraded to version 26 and everything works fine. So I guess this is the problem here 👀?

**Comment by ilyabo** [comment]
If the versions didn't match in the lock file, that's probably because you had installed different versions. Try to make sure that both versions you install are the same:

`pnpm add @flowmap.gl/data@8.0.0-alpha27 @flowmap.gl/layers@8.0.0-alpha27`

**Comment by lalagis** [comment]
When I try `pnpm add @flowmap.gl/data@8.0.0-alpha27 @flowmap.gl/layers@8.0.0-alpha27`, I got:
```zsh
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @flowmap.gl/data@8.0.0-alpha27

This error happened while installing a direct dependency of /Users/naigai/Documents/code/flow_vis

The latest release of @flowmap.gl/data is "8.0.0-alpha.0".

Other releases are:
  * next: 8.0.0-alpha.27

If you need the full list of all 29 published versions run "$ pnpm view @flowmap.gl/data versions".
```
Then I run: `pnpm view @flowmap.gl/data versions`:
```zsh
[
  '8.0.0-alpha.0',  '8.0.0-alpha.1',
  '8.0.0-alpha.2',  '8.0.0-alpha.3',
  '8.0.0-alpha.4',  '8.0.0-alpha.5',
  '8.0.0-alpha.6',  '8.0.0-alpha.7',
  '8.0.0-alpha.8',  '8.0.0-alpha.9',
  '8.0.0-alpha.10', '8.0.0-alpha.11',
  '8.0.0-alpha.12', '8.0.0-alpha.13',
  '8.0.0-alpha.14', '8.0.0-alpha.15',
  '8.0.0-alpha.16', '8.0.0-alpha.17',
  '8.0.0-alpha.18', '8.0.0-alpha.19',
  '8.0.0-alpha.20', '8.0.0-alpha.21',
  '8.0.0-alpha.22', '8.0.0-alpha.23',
  '8.0.0-alpha.24', '8.0.0-alpha.25',
  '8.0.0-alpha.26', '8.0.0-alpha.27',
  '8.0.0-y.14'
]
```
After I edit the dependencies in `package.json`
```json
  "dependencies": {
    "@flowmap.gl/data": "8.0.0-alpha.27",
    "@flowmap.gl/layers": "8.0.0-alpha.27",
  },
```
and `pnpm install`, works fine.
The issue I mentioned should only occur when using `pnpm upgrade` to upgrade all dependencies to the latest version.

**Comment by ilyabo** [comment]
Ah I see, it considers `@flowmap.gl/data@8.0.0-y.14` as the latest, that's why. I will try to publish the next version as 8.0.1. Hopefully, that will solve it. Thanks for letting me know!

**Comment by ilyabo** [comment]
Should be solved now
