### ISSUE TITLE
Clustering becomes laggy on large dataset

### ISSUE THREAD

**Issue by kiyosoft** [visgl/flowmap.gl#42]
Hi thank you for this awesome library. I am integrating it with my project, and I noticed that clustering becomes sluggish when I try it with large data set with more than a million flows, I tested the same data in flowmap city it works fine there. Any help is appreciated.

**Comment by kiyosoft** [comment]
I just found about Flowmap city is aggregating flows with the same source - destination pairs thank you

**Comment by ilyabo** [comment]
Yes, Flowmap City is doing it more efficiently. If you want to embed it in your app, consider [Flowmap City SDK](https://docs.flowmap.city/sdk)
